export const locationOptions = [
  'Banashankari',
  'Basavanagudi',
  'Mysore Road',
  'Jayanagar',
  'Kumaraswamy Layout',
  'Rajarajeshwari Nagar',
  'Vijay Nagar',
  'Uttarahalli',
  'Jp Nagar',
  'South Bangalore',
  'City Market',
  'Nagarbhavi',
  'Bannerghatta Road',
  'Btm',
  'Kanakapura Road',
  'Bommanahalli',
  'Not Available',
  'Cv Raman Nagar',
  'Electronic City',
  'Hsr',
  'Marathahalli',
  'Sarjapur Road',
  'Wilson Garden',
  'Shanti Nagar',
  'Koramangala 5Th Block',
  'Koramangala 8Th Block',
  'Richmond Road',
  'Koramangala 7Th Block',
  'Jalahalli',
  'Koramangala 4Th Block',
  'Bellandur',
  'Whitefield',
  'East Bangalore',
  'Old Airport Road',
  'Indiranagar',
  'Koramangala 1St Block',
  'Frazer Town',
  'Rt Nagar',
  'Mg Road',
  'Brigade Road',
  'Lavelle Road',
  'Church Street',
  'Ulsoor',
  'Residency Road',
  'Shivajinagar',
  'Infantry Road',
  'St. Marks Road',
  'Cunningham Road',
  'Race Course Road',
  'Commercial Street',
  'Vasanth Nagar',
  'Hbr Layout',
  'Domlur',
  'Ejipura',
  'Jeevan Bhima Nagar',
  'Old Madras Road',
  'Malleshwaram',
  'Seshadripuram',
  'Kammanahalli',
  'Koramangala 6Th Block',
  'Majestic',
  'Langford Town',
  'Central Bangalore',
  'Sanjay Nagar',
  'Brookefield',
  'Itpl Main Road, Whitefield',
  'Varthur Main Road, Whitefield',
  'Kr Puram',
  'Koramangala 2Nd Block',
  'Koramangala 3Rd Block',
  'Koramangala',
  'Hosur Road',
  'Rajajinagar',
  'Banaswadi',
  'North Bangalore',
  'Nagawara',
  'Hennur',
  'Kalyan Nagar',
  'New Bel Road',
  'Jakkur',
  'Rammurthy Nagar',
  'Thippasandra',
  'Kaggadasapura',
  'Hebbal',
  'Kengeri',
  'Sankey Road',
  'Sadashiv Nagar',
  'Basaveshwara Nagar',
  'Yeshwantpur',
  'West Bangalore',
  'Magadi Road',
  'Yelahanka',
  'Sahakara Nagar',
  'Peenya',
];

export const typeOptions = [
  'Buffet',
  'Cafes',
  'Delivery',
  'Desserts',
  'Dine-out',
  'Drinks & nightlife',
  'Pubs and bars',
];
